import { registerAppTool } from "@modelcontextprotocol/ext-apps/server";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import type { WebConnectorProofController } from "./web-connector-proof.js";

const NO_APP_META = { _meta: {} } as const;
const HEX_64_PATTERN = /^[0-9a-f]{64}$/;

export function registerWebConnectorTools(input: {
  server: McpServer;
  proof: Pick<
    WebConnectorProofController,
    "startConnectorAccess" | "acceptProbe" | "getProofStatus"
  >;
}): void {
  const { server, proof } = input;

  registerAppTool(
    server,
    "web_connector_start",
    {
      title: "Start connector proof",
      description:
        "WEB-CONNECTOR-1 only. Starts one bounded asynchronous proof that a fresh ChatGPT Web conversation can discover and invoke DevSpace. Returns a proof ID immediately after retaining the run, then launches one fixed acceptance prompt without waiting for the callback. It does not capture assistant output, open a workspace, read files, or continue the spawned conversation.",
      inputSchema: {},
      ...NO_APP_META,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async () => {
      const acknowledgement = proof.startConnectorAccess();
      return {
        content: [
          {
            type: "text" as const,
            text: "WEB-CONNECTOR-1 connector proof started. Use web_connector_status with the returned proofId.",
          },
        ],
        structuredContent: acknowledgement,
      };
    },
  );

  registerAppTool(
    server,
    "web_connector_probe",
    {
      title: "Accept connector callback",
      description:
        "WEB-CONNECTOR-1 internal bounded callback. Invoke exactly once only when a newly launched ChatGPT conversation contains an exact 64-character challenge generated by web_connector_start. This tool consumes that challenge and mutates only retained ephemeral run state. It does not open a workspace, access files, run commands, or change persistent state.",
      inputSchema: {
        challenge: z
          .string()
          .regex(HEX_64_PATTERN)
          .describe(
            "Exact one-time WEB-CONNECTOR-1 challenge supplied in the launched conversation.",
          ),
      },
      ...NO_APP_META,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false,
      },
    },
    async ({ challenge }) => {
      const acknowledgement = proof.acceptProbe(challenge);
      return {
        content: [
          {
            type: "text" as const,
            text: "WEB-CONNECTOR-1 callback accepted. Stop without invoking another tool.",
          },
        ],
        structuredContent: acknowledgement,
      };
    },
  );

  registerAppTool(
    server,
    "web_connector_status",
    {
      title: "Read connector proof status",
      description:
        "WEB-CONNECTOR-1 only. Retrieves the retained bounded state for one proof ID. Returns pending, succeeded, failed, or expired metadata without accessing assistant output, browser content, workspaces, files, commands, or persistent storage.",
      inputSchema: {
        proofId: z
          .string()
          .regex(HEX_64_PATTERN)
          .describe("Exact WEB-CONNECTOR-1 proof ID returned by web_connector_start."),
      },
      ...NO_APP_META,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ proofId }) => {
      const acknowledgement = proof.getProofStatus(proofId);
      return {
        content: [
          {
            type: "text" as const,
            text: `WEB-CONNECTOR-1 proof status: ${acknowledgement.status}.`,
          },
        ],
        structuredContent: acknowledgement,
      };
    },
  );
}
