import { registerAppTool } from "@modelcontextprotocol/ext-apps/server";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import type { WebConnectorProofController } from "./web-connector-proof.js";

const NO_APP_META = { _meta: {} } as const;

export function registerWebConnectorTools(input: {
  server: McpServer;
  proof: Pick<WebConnectorProofController, "proveConnectorAccess" | "acceptProbe">;
}): void {
  const { server, proof } = input;

  registerAppTool(
    server,
    "web_connector_proof",
    {
      title: "Verify DevSpace connector",
      description:
        "WEB-CONNECTOR-1 only. Use after the user explicitly requests one bounded proof that a fresh ChatGPT Web conversation can discover and invoke the connected DevSpace connector. Launches one fresh conversation with a fixed acceptance prompt, waits for that conversation to invoke the read-only web_connector_probe tool, and returns only proof metadata. It does not capture assistant output, open a workspace, read files, or continue the spawned conversation.",
      inputSchema: {},
      ...NO_APP_META,
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async () => {
      const acknowledgement = await proof.proveConnectorAccess();
      return {
        content: [
          {
            type: "text" as const,
            text: "WEB-CONNECTOR-1 connector proof succeeded.",
          },
        ],
        structuredContent: acknowledgement,
      };
    },
  );

  registerAppTool(
    server,
    "web_connector_probe",
    {
      title: "Accept connector probe",
      description:
        "WEB-CONNECTOR-1 internal read-only probe. Invoke exactly once only when a newly launched ChatGPT conversation contains an exact 64-character challenge generated by web_connector_proof. This tool validates and consumes that one-time challenge without opening a workspace, reading files, running commands, or changing persistent state.",
      inputSchema: {
        challenge: z
          .string()
          .regex(/^[0-9a-f]{64}$/)
          .describe(
            "Exact one-time WEB-CONNECTOR-1 challenge supplied in the launched conversation.",
          ),
      },
      ...NO_APP_META,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false,
      },
    },
    async ({ challenge }) => {
      const acknowledgement = proof.acceptProbe(challenge);
      return {
        content: [
          {
            type: "text" as const,
            text: "WEB-CONNECTOR-1 probe accepted. Stop without invoking another tool.",
          },
        ],
        structuredContent: acknowledgement,
      };
    },
  );
}
